services:
  agente:
    build: .
    user: "1000:1000"
    container_name: ${CLAUDE_CONTAINER_NAME}
    
    stdin_open: true
    tty: true

    volumes:
      - /lab/docker/ubuntu-app:/data   # seus arquivos
      - openclaude_config:/home/ubuntu/.openclaude

    # Mapeia sua pasta de trabalho
    # volumes:
    #   - /lab/docker/ubuntu-app:/app
    #   - openclaude_config:/home/ubuntu/.openclaude
    
    # Mapeia o host
    extra_hosts:
      - "${EXTRA_HOSTS}"

    env_file:
      - .env
      
volumes:
  openclaude_config: