CREATE TABLE fornecedores (
    id    NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR2(100) NOT NULL,
    pais  VARCHAR2(50)  NOT NULL,
    ativo NUMBER(1)     DEFAULT 1
);

CREATE TABLE setores (
    id   NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50)  NOT NULL
);

CREATE TABLE produtos (
    id             NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo         VARCHAR2(20)  NOT NULL UNIQUE,
    descricao      VARCHAR2(100) NOT NULL,
    categoria      VARCHAR2(50)  NOT NULL,
    preco_unitario NUMBER(10,2)  NOT NULL,
    fornecedor_id  NUMBER,
    CONSTRAINT fk_prod_forn 
        FOREIGN KEY (fornecedor_id)
        REFERENCES fornecedores(id)
        ON DELETE CASCADE
);

CREATE TABLE estoque (
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id NUMBER NOT NULL,
    setor_id   NUMBER NOT NULL,
    quantidade NUMBER NOT NULL DEFAULT 0,
    minimo     NUMBER NOT NULL DEFAULT 50,
    atualizado DATE   DEFAULT SYSDATE NOT null,
    CONSTRAINT fk_est_prod 
        FOREIGN KEY (produto_id) 
        REFERENCES produtos(id),
    CONSTRAINT fk_est_set  
        FOREIGN KEY (setor_id) 
        REFERENCES setores(id)
);
 
CREATE TABLE pedidos (
    id            NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id    NUMBER        NOT NULL,
    fornecedor_id NUMBER        NOT NULL,
    quantidade    NUMBER        NOT NULL,
    status        VARCHAR2(20)  DEFAULT 'pendente',
    data_pedido   DATE          DEFAULT SYSDATE,
    data_entrega  DATE,
    CONSTRAINT fk_ped_prod 
	    FOREIGN KEY (produto_id)    
	    REFERENCES produtos(id),
    CONSTRAINT fk_ped_forn 
        FOREIGN KEY (fornecedor_id) 
        REFERENCES fornecedores(id)
);
 
CREATE TABLE producao (
    id        NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setor_id  NUMBER        NOT NULL,
    data      DATE          NOT NULL,
    meta      NUMBER        NOT NULL,
    realizado NUMBER        NOT NULL,
    turno     VARCHAR2(10)  NOT NULL,
    CONSTRAINT fk_producao_set 
        FOREIGN KEY (setor_id) 
        REFERENCES setores(id)
);
 
CREATE TABLE alunos (
    id     NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome   VARCHAR2(100) NOT NULL,
    status VARCHAR2(100) DEFAULT 'desconhecido' NOT NULL 
);
 
CREATE TABLE professores (
    id         NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR2(100) DEFAULT 'desconhecido' NOT null,
    quantidade NUMBER        NULL
);

CREATE OR REPLACE PROCEDURE resultado(
	p_produto_id IN NUMBER,
	p_resutado OUT VARCHAR2
) AS 
	lo_var_estoque_atual NUMBER;
BEGIN
	
	SELECT quantidade INTO lo_var_estoque_atual
	FROM estoque
	WHERE produto_id = p_produto_id;

	IF lo_var_estoque_atual > 100 THEN
		p_resutado := 'Estoque ok';
	ELSE
		p_resutado := 'Estoque baixo';
	END IF;

EXCEPTION
	
	WHEN NO_DATA_FOUND THEN
		p_resutado := 'Produto não cadastrado';
    WHEN TOO_MANY_ROWS THEN
        p_resutado := '"Erro: ID duplicado na tabela"';
END;

