CREATE TABLE fornecedores (
    id    NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR2(100) NOT NULL,
    pais  VARCHAR2(50)  NOT NULL,
    ativo NUMBER(1)     DEFAULT 1
);

CREATE TABLE setores (
    id   NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(50)  NOT NULL
);

CREATE TABLE produtos (
    id             NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo         VARCHAR2(20)  NOT NULL UNIQUE,
    descricao      VARCHAR2(100) NOT NULL,
    categoria      VARCHAR2(50)  NOT NULL,
    preco_unitario NUMBER(10,2)  NOT NULL,
    fornecedor_id  NUMBER,
    CONSTRAINT fk_prod_forn 
    	FOREIGN KEY (fornecedor_id)
    	REFERENCES fornecedores(id)
    	ON DELETE CASCADE
);